### ISSUE TITLE
Not found [-I iface] parameter : Specific interface 

### ISSUE THREAD

**Issue by mcspx** [go-ping/ping#111]
Can you implement for all parameter like ping on linux :)

usage: ping [-AaDdfnoQqRrv] [-c count] [-G sweepmaxsize]
            [-g sweepminsize] [-h sweepincrsize] [-i wait]
            [-l preload] [-M mask | time] [-m ttl] [-p pattern]
            [-S src_addr] [-s packetsize] [-t timeout][-W waittime]
            [-z tos] host
       ping [-AaDdfLnoQqRrv] [-c count] [-I iface] [-i wait]
            [-l preload] [-M mask | time] [-m ttl] [-p pattern] [-S src_addr]
            [-s packetsize] [-T ttl] [-t timeout] [-W waittime]
            [-z tos] mcast-group

Thank you
Mon

**Comment by CHTJonas** [comment]
The `cmd/ping/ping.go` file does not aim to replicate the full spectrum of functionality found in the traditional UNIX `/bin/ping` binary or to be a 'rewrite in Go'. Rather, it is intended as a demonstration of how you can use the `github.com/go-ping/ping` package within your own applications.

As such, I think that implementing all parameters is somewhat out of scope so I will respectfully close this.
