### ISSUE TITLE
Running multiple pingers in concurrent causes unexpected high CPU usage

### ISSUE THREAD

**Issue by chenlujjj** [go-ping/ping#125]
When running multiple pingers in concurrent, I found that the program used too much CPU.

The code snippet to reproduce this problem is below.

```go
const N = 20

func main() {
	var wg sync.WaitGroup
	for i := 0; i < N; i++ {
		wg.Add(1)
		go func() {
			GoPing()
			wg.Done()
		}()
	}
	wg.Wait()
}


func GoPing() {
	pinger, err := ping.NewPinger("www.baidu.com")
	if err != nil {
		log.Fatal(err)
	}
	pinger.Count = 30
	pinger.OnRecv = func(pkt *ping.Packet) {
		fmt.Printf("%d bytes from %s: icmp_seq=%d ttl=%d time=%v\n",
			pkt.Nbytes, pkt.IPAddr, pkt.Seq, pkt.Ttl, pkt.Rtt)
	}

	pinger.OnFinish = func(stats *ping.Statistics) {
		fmt.Printf("\n--- %s ping statistics ---\n", stats.Addr)
		fmt.Printf("%d packets transmitted, %d packets received, %v%% packet loss\n",
			stats.PacketsSent, stats.PacketsRecv, stats.PacketLoss)
		fmt.Printf("round-trip min/avg/max/stddev = %v/%v/%v/%v\n",
			stats.MinRtt, stats.AvgRtt, stats.MaxRtt, stats.StdDevRtt)
	}
	err = pinger.Run()
	if err != nil {
		log.Fatal(err)
	}
}
```

The `htop` shows the program uses about 5% CPU when concurrency (N in the code) is 20.

For comparison, executing shell command `ping`, the program costs about 0.1% CPU.

The cpuprofile shows that majority CPU time was cost by `golang.org/x/net/internal/socket.(*Conn).recvMsg`.

**Comment by CHTJonas** [comment]
I think this is the same thing as #139. Basically it looks like the `(*Pinger).recvICMP(*icmp.PacketConn, chan<- *packet, *sync.WaitGroup)` function should be run once in a global context rather than on a per-pinger basis.

That ticket has a bit more detail so I'll close in favour of that one!
