### ISSUE TITLE
Reduce chance of ICMP packet ID collisions

### ISSUE THREAD

**Issue by CHTJonas** [go-ping/ping#131]
As reported by @ssoroka in #130: the `Pinger.id` field is set to a randomly generated number but only in the range 0 to 32767 rather than 0 to 2147483647 (15 bits rather than 31 bits, accounting for sign). Someone running a large number of pings in parallel has a not-insignificant chance of packet ID collision.

https://github.com/go-ping/ping/blob/3300c582a663c5bce1d0ecf1868107da0ae38829/ping.go#L98

The `ID` field of the `Echo` struct in `golang.org/x/net/icmp` [[ref](https://github.com/golang/net/blob/4acb7895a057/icmp/echo.go#L16)] is an `int` type so we should try and use the full bit space of that.

**Comment by SuperQ** [comment]
I'm wondering if it would also be useful to have an optional extra ID in the ICMP message body. You could stuff a UUID into the message body and include that as part of the "is this the right Pinger" logic.

**Comment by ssoroka** [comment]
@SuperQ is this the purpose of the `Tracker` field, or do we essentially use it as that anyway?

**Comment by SuperQ** [comment]
@ssoroka That's a per-packet tracking.

**Comment by ssoroka** [comment]
Anyone have any idea why switching to MaxInt32 doesn't work? the spec seems to say this is an int32 field

**Comment by CHTJonas** [comment]
Yeah I'm not sure why it's not working... 🤔  Wireshark clearly shows that the echo request packets are leaving and that replies are being received by the OS so it's reasonable to assume that the issue is somewhere in the deserialisation chain.

This is what I observe when pinging Cloudflare:

<img width="1199" src="https://user-images.githubusercontent.com/17813061/106369638-0a36e980-634b-11eb-9c5f-d09bc094417c.png">

**Comment by ssoroka** [comment]
Looks like the problem might be coming from golang.org/x/net/icmp/echo.go:31
```go
// Marshal implements the Marshal method of MessageBody interface.
func (p *Echo) Marshal(proto int) ([]byte, error) {
	b := make([]byte, 4+len(p.Data))
	binary.BigEndian.PutUint16(b[:2], uint16(p.ID))
	binary.BigEndian.PutUint16(b[2:4], uint16(p.Seq))
	copy(b[4:], p.Data)
	return b, nil
}
```

**Comment by ssoroka** [comment]
It looks like this matches the ICMP spec . https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol#Timestamp

If in fact it's only 16 bits, which it appears to be, then it explains why we're having issues. If that's all there is to play with the only other thing I can think of is starting the sequence numbers at random places in the 2^16 space, rather than always at 0, and making sure they roll over to 0 properly.

we can also use MaxUint16 to double the addresses we get, rather than MaxInt16

**Comment by ssoroka** [comment]
confirmed this works, Only downside is the sequence number is visible to the user
```sh
> go run .\cmd\ping\ping.go --privileged google.ca
PING google.ca (172.217.164.227):
24 bytes from 172.217.164.227: icmp_seq=5518 time=28.7935ms ttl=0
24 bytes from 172.217.164.227: icmp_seq=5521 time=28.2054ms ttl=0
24 bytes from 172.217.164.227: icmp_seq=5522 time=43.8518ms ttl=0
24 bytes from 172.217.164.227: icmp_seq=5523 time=37.1334ms ttl=0
24 bytes from 172.217.164.227: icmp_seq=5524 time=38.5358ms ttl=0
24 bytes from 172.217.164.227: icmp_seq=5525 time=28.1251ms ttl=0
24 bytes from 172.217.164.227: icmp_seq=5526 time=28.9425ms ttl=0

--- google.ca ping statistics ---
9 packets transmitted, 7 packets received, 22.22222222222222% packet loss
round-trip min/avg/max/stddev = 28.1251ms/33.369642ms/43.8518ms/5.921461ms
> go run .\cmd\ping\ping.go --privileged google.ca
PING google.ca (172.217.164.227):
24 bytes from 172.217.164.227: icmp_seq=12030 time=30.4058ms ttl=0
24 bytes from 172.217.164.227: icmp_seq=12031 time=32.5532ms ttl=0
24 bytes from 172.217.164.227: icmp_seq=12032 time=37.57ms ttl=0
24 bytes from 172.217.164.227: icmp_seq=12033 time=36.7702ms ttl=0

--- google.ca ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max/stddev = 30.4058ms/34.3248ms/37.57ms/2.958396ms
```

**Comment by CHTJonas** [comment]
Thanks for digging through the Golang sodlib and spec. By playing around and hardcoding values for `Pinger.id` I've worked out that the largest value it can take is `math.MaxUint16` which concurs with that. Also the fact that Wireshark displays the id as `0xFFFF`.

**Comment by ssoroka** [comment]
... could make random initial sequences a function you could call to enable this if always running it is undesirable.

**Comment by CHTJonas** [comment]
Regarding adding some more entropy to the sequence number, I wonder if by default we should stick to starting from 0 but maybe have e.g. a `pinger.UseRandomFirstSeq(true)` method, similar to how we have `pinger.SetPrivileged(true)`, for anyone who does want do to that.

**Comment by ssoroka** [comment]
I think we're on the same page. :D

**Comment by CHTJonas** [comment]
That said, I'm not sure randomising seq numbers gets us much. If a larger number of pingers are created in a very concurrent environment and two happen to have the same randomly-generated ID then any echo replies will filter through to one of them which will either count it as a genuine reply, or (pending the merge of #130) see it as a duplicate rather than a packet meant for the other pinger.

**Comment by ssoroka** [comment]
ah. I think you're right. I think we need to also use the tracker to confirm uniqueness... if we do that maybe it's not necessary to do the rest.

**Comment by ssoroka** [comment]
which it looks like it already does.

**Comment by CHTJonas** [comment]
Cool. Do you want to open the world's shortest PR to change it to `math.MaxUint16`? (it actually has to be a PR even if one of us opens it since we can't push directly to `master` 😉)

**Comment by ssoroka** [comment]
will do.
