### ISSUE TITLE
help me!!!     windows 10 no icmp protocol ? 

### ISSUE THREAD

**Issue by dragon1102** [go-ping/ping#149]
socket: The requested protocol has not been configured into the system, or no implementation for it exists.

**Comment by CHTJonas** [comment]
Did you read the [Windows section of the README](https://github.com/go-ping/ping#windows)?

**Comment by dragon1102** [comment]
> Did you read the [Windows section of the README](https://github.com/go-ping/ping#windows)?
Sorry, I didn’t look carefully at the beginning, but I closed the issue after finding a solution
