### ISSUE TITLE
[features request] timeout as error

### ISSUE THREAD

**Issue by yxxhero** [go-ping/ping#165]
[features request] timeout as error

**Comment by SuperQ** [comment]
This seems like a duplicate of https://github.com/go-ping/ping/issues/50

**Comment by yxxhero** [comment]
Can I continue https://github.com/go-ping/ping/issues/50 work?  @SuperQ

**Comment by SuperQ** [comment]
Yes, we need some foudnations as @CHTJonas pointed out.
