### ISSUE TITLE
Lake of srcAddr to send icmp

### ISSUE THREAD

**Issue by limbo127** [go-ping/ping#174]
Hello, 
we need to set the addr source of the paquet, because we have a lot of ipv6 alias on interface, but we need to specify as

 net.DialUDP("udp6", &addrsrc, &addrdst)

regards, 
Nicolas

**Comment by CHTJonas** [comment]
Can you not do this by setting `pinger.Source`? See [docs](https://pkg.go.dev/github.com/go-ping/ping#Pinger).

**Comment by limbo127** [comment]
Oh yes, sorry I do not seen that.
Regards

Le ven. 30 juil. 2021 à 22:21, Charlie Jonas ***@***.***> a
écrit :
