### ISSUE TITLE
Measured times are greater then regular ping

### ISSUE THREAD

**Issue by manio** [go-ping/ping#179]
Hi,
I am testing go-ping and comparing it to a regular ping utility (Debian Linux x86_64).
I am pinging a host in LAN to have a stable testing environment. Here are the results from a ping:
```
285 packets transmitted, 285 received, 0% packet loss, time 286287ms
rtt min/avg/max/mdev = 0.507/0.665/0.980/0.062 ms
```
The problem I can see is that using a go-ping gives averages to be about 100ms higher (calling it multiple times with sending single request as in the code) and it's not uncommon to have values above 1ms which doesn't happen at all with a ping tool.
I am testing it using this [code](https://gist.github.com/alkuzad/b816cb0b4c325b0e13de80acc964550a).

Here is the comparison of the resulted ping times from telegraf:
![image](https://user-images.githubusercontent.com/583157/132302253-d98fa765-8112-4241-8035-1454b116b229.png)
First part of the graph is a go-ping results, then I switched to a regular ping utility.

Is it a go-runtime overhead? Can we get rid of it and make the results in-pair with a regular ping tool?

**Comment by CHTJonas** [comment]
Go is a GC-ed language so massive latency spikes like that *might* just be par for the course. Alternatively it might be related to #139.
