### ISSUE TITLE
Non-privileged scenarios do not work

### ISSUE THREAD

**Issue by HuKeping** [go-ping/ping#180]
After commit 62f79f1f4f36fc821eebb131548270d4d8b68653 upstream, the go-ping program blocks the received ICMP packets because the received ICMP identifier is different from the senter's echo identifier

We think it may caused by  the Linux kernel automatically assigns an identifier as the local receive port number in non-privileged cases.

**Comment by HuKeping** [comment]
ping @mem

**Comment by CHTJonas** [comment]
I'm not experiencing this issue.

```
chtj2@pip:/tmp/chtj2$ uname -a
Linux pip 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

chtj2@pip:/tmp/chtj2$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

chtj2@pip:/tmp/chtj2$ go version
go version go1.15.2 linux/amd64

chtj2@pip:/tmp/chtj2$ git clone https://github.com/go-ping/ping.git
Cloning into 'ping'...
remote: Enumerating objects: 290, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 290 (delta 8), reused 12 (delta 4), pack-reused 267
Receiving objects: 100% (290/290), 1.28 MiB | 2.00 MiB/s, done.
Resolving deltas: 100% (144/144), done.

chtj2@pip:/tmp/chtj2$ cd ping/

chtj2@pip:/tmp/chtj2/ping$ go run cmd/ping/ping.go google.com
go: downloading golang.org/x/net v0.0.0-20210316092652-d523dce5a7f4
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: downloading github.com/google/uuid v1.2.0
go: downloading golang.org/x/sys v0.0.0-20210315160823-c6e025ad8005
PING google.com (142.250.187.238):
32 bytes from 142.250.187.238: icmp_seq=0 time=6.165858ms ttl=116
32 bytes from 142.250.187.238: icmp_seq=1 time=6.051684ms ttl=116
32 bytes from 142.250.187.238: icmp_seq=2 time=6.041586ms ttl=116
32 bytes from 142.250.187.238: icmp_seq=3 time=6.016118ms ttl=116
32 bytes from 142.250.187.238: icmp_seq=4 time=6.064066ms ttl=116
32 bytes from 142.250.187.238: icmp_seq=5 time=5.871934ms ttl=116
32 bytes from 142.250.187.238: icmp_seq=6 time=5.958188ms ttl=116
32 bytes from 142.250.187.238: icmp_seq=7 time=6.023026ms ttl=116
^C
--- google.com ping statistics ---
8 packets transmitted, 8 packets received, 0 duplicates, 0% packet loss
round-trip min/avg/max/stddev = 5.871934ms/6.024059ms/6.165858ms/79.312µs
```

@HuKeping, please could you elaborate on what Linux distribution and kernel version you are running?

Do you have some kernel code that you link to or something else that supports your hypothesis that Linux is assigning the receive port number as the identifier?

**Comment by RabeaWahab** [comment]
I am having this issue, running the same commands as @CHTJonas , on `Macbook AIR M1 - Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64`

```
➜  services git clone https://github.com/go-ping/ping.git
Cloning into 'ping'...
remote: Enumerating objects: 290, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 290 (delta 8), reused 12 (delta 4), pack-reused 267
Receiving objects: 100% (290/290), 1.28 MiB | 2.58 MiB/s, done.
Resolving deltas: 100% (144/144), done.

➜  services cd ping

➜  ping git:(master) go run cmd/ping/ping.go google.com
go: downloading golang.org/x/net v0.0.0-20210316092652-d523dce5a7f4
go: downloading golang.org/x/sys v0.0.0-20210315160823-c6e025ad8005
PING google.com (172.253.124.100): ------> left it running for about 30 seconds
^C
--- google.com ping statistics ---
121 packets transmitted, 0 packets received, 0 duplicates, 100% packet loss
round-trip min/avg/max/stddev = 0s/0s/0s/0s

**Comment by fkr** [comment]
@RabeaWahab while on macOS no proper error is thrown on (other) BSDs (such as OpenBSD and FreeBSD) proper errors are given, raw sockets are only for use by superusers. I actually ran into this couple weeks ago and still wanted to track down why no hard error is thrown on macOS.

**Comment by mem** [comment]
I'm clueless when it comes to Darwin... on Linux, there's something that you have to configure to make rootless ping work ([the group range that is allowed to send ICMP packets without privileges](https://man7.org/linux/man-pages/man7/icmp.7.html)).

Is there something similar for Darwin, or is there something similar that is specific to MacOS? [This](https://apple.stackexchange.com/questions/312857/how-does-macos-allow-standard-users-to-ping) suggests it's enabled by default as long as you use SOCK_DGRAM (UDP/IP), which this code does.
