### ISSUE TITLE
avgRtt is sometimes negative

### ISSUE THREAD

**Issue by YouZhengChuan** [go-ping/ping#194]
![image](https://user-images.githubusercontent.com/3882312/146713599-7c94a88a-9ece-4a08-a3ea-7b5d3bc45720.png)
The probability is very low, but there is a possibility of negative numbers.

**Comment by YouZhengChuan** [comment]
![image](https://user-images.githubusercontent.com/3882312/146713948-a3438861-9b28-47fd-b3d0-c10fba23ad20.png)

rt_min is negative，So Packet.Rtt is wrong。

**Comment by CHTJonas** [comment]
What endpoint(s) are you pinging when you experience this? On which platform (OS/architecture) are you experiencing this? Could you include full sample code that replicates the issue?

**Comment by YouZhengChuan** [comment]
![image](https://user-images.githubusercontent.com/3882312/196080281-abda08d8-9779-4644-9e6d-a0350ca584e6.png)
From recent results, this only happens in devices with "ARM64" architecture, the OS version is "Debian GNU/Linux 9 (stretch)"; the destination addresses are both IP4 and IP6.

pinger code:

```golang
pinger := goPing.New(IP)
pinger.SetNetwork(network) // ip4, ip6, ip
if err := pinger.Resolve(); err != nil { return err }
pinger.Source = bindAddr
pinger.SetPrivileged(true)
pinger.Timeout = timeout
pinger.Interval = interval
pinger.Count = int(pktCount)
pinger.Size = int(pktBytes)
pinger.OnFinish = func(stats *goPing.Statistics) {
	result.PktLoss = stats.PacketLoss
	result.RtMax = int64(stats.MaxRtt) / 1e6 // Milliseconds
	result.RtAvg = int64(stats.AvgRtt) / 1e6 // Milliseconds
	result.RtMin = int64(stats.MinRtt) / 1e6 // Milliseconds
}
if err := pinger.Run(); err != nil { return err }
```
