### ISSUE TITLE
cannot find package

### ISSUE THREAD

**Issue by fgsoftware1** [go-ping/ping#212]
cannot find package "github.com/go-ping/ping" in any of:
	/usr/lib/go-1.17/src/github.com/go-ping/ping (from $GOROOT)
	/home/fgygh/go/src/github.com/go-ping/ping (from $GOPATH)

**Comment by CHTJonas** [comment]
Have you tried `go get`'ing it?

**Comment by fgsoftware1** [comment]
> Have you tried `go get`'ing it?

yeah. i tried
