### ISSUE TITLE
How to get network interface used to make the ping?

### ISSUE THREAD

**Issue by santosh** [go-ping/ping#217]
I have a use case where I have to know which interface was used to make the ping. Is it possible with this library to get the interface?

**Comment by alexeykudr** [comment]
Hey, i have same question, just want use like ping -I 192.168.99.100

maybe your find how to do it ?

**Comment by alexeykudr** [comment]
> I have a use case where I have to know which interface was used to make the ping. Is it possible with this library to get the interface?

Maybe this is solution for you

	pinger, err := ping.NewPinger("www.google.com")
	pinger.Source = "192.168.17.100"

Where source is your interface, try to ens0 like this, maybe will also work

**Comment by santosh** [comment]
I was more interested in know which interface was used. 

If I am correct, what you are suggesting is to:

1. First find out all the interfaces on the device.
2. Try making ping request for N number of time where N is the number of interfaces. 

Am I correct?

**Comment by santosh** [comment]
Well yeah. If there is no way then the only way is to bruteforce. I suppose I should launch N goroutines and the only ping which succeeds will be my interface.
