### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by reimda** [go-ping/ping#221]
I'm a maintainer of the telegraf project. We have received a [request](https://github.com/influxdata/telegraf/pull/11836) to migrate away from go-ping and use a fork, [pro-bing](https://github.com/prometheus-community/pro-bing).

It's been four months since there's been a commit here and there are a few PRs that need maintainer attention. @CHTJonas @sparrc could you respond and share your plans for the org and repo? Should projects like telegraf migrate to a fork if they need module dependency updates, bugfixes, or new features?

**Comment by SuperQ** [comment]
As one of the 3 `go-ping/ping` maintainers, I vote abandoned.

**Comment by CHTJonas** [comment]
As one of the other maintainers, I second @SuperQ.

**Comment by CHTJonas** [comment]
Suggested fork is https://github.com/prometheus-community/pro-bing
