### ISSUE TITLE
overflow when calculating stdDev

### ISSUE THREAD

**Issue by zhangzhongjun** [go-ping/ping#235]
https://github.com/go-ping/ping/blob/caaf2b72ea569a64c10e0af4b1e4828e8fc42f0e/ping.go#L301

In Go, time.Duration is a type based on a 64-bit signed integer (int64), where the value is expressed in nanoseconds. The range of time.Duration is therefore determined by the range of int64, which can hold values from -9223372036854775808 to 9223372036854775807.

Such a case will occur when there is severe network jitter.

**Comment by Hipska** [comment]
# Deprecated

Due to lack of maintainers and access, this library is no longer maintained.
There is a new actively maintained fork: https://github.com/prometheus-community/pro-bing
