### ISSUE TITLE
How to send packets size with 60000？

### ISSUE THREAD

**Issue by hel2o** [go-ping/ping#34]
when i set pinger.Size = 60000 ,but packets is not send
![default](https://user-images.githubusercontent.com/14226648/46844671-af3ff800-ce0a-11e8-9e4d-5c94dd02e502.png)

![default](https://user-images.githubusercontent.com/14226648/46844607-6c7e2000-ce0a-11e8-9b03-2e7b7d3945fe.png)

**Comment by sparrc** [comment]
I believe this may have been fixed by #45, can you update to the latest commit of go-ping and try again?

**Comment by SuperQ** [comment]
I think there are still issues with the size option.

When I set `p.Size = 256`, tcpdump says the packet length is 394.

When I set `p.Size = 321`, tcpdump says the packet length is 478.

When I set `p.Size = 322`, tcpdump says the packet length is 482, and panics my prober.

```
panic: runtime error: slice bounds out of range

goroutine 39 [running]:
github.com/superq/smokeping_prober/ping.(*Pinger).processPacket(0xc000159110, 0xc0001609c0, 0x4, 0x3)
	/home/ben/go/src/github.com/superq/smokeping_prober/ping/ping.go:435 +0x6be
github.com/superq/smokeping_prober/ping.(*Pinger).run(0xc000159110)
	/home/ben/go/src/github.com/superq/smokeping_prober/ping/ping.go:321 +0x4e1
github.com/superq/smokeping_prober/ping.(*Pinger).Run(0xc000159110)
	/home/ben/go/src/github.com/superq/smokeping_prober/ping/ping.go:270 +0x2b
created by main.main
	/home/ben/go/src/github.com/superq/smokeping_prober/main.go:95 +0xf09
```

**Comment by sparrc** [comment]
I'm going to hazard a guess that this has something to do with the code still referencing timeSliceLength, which is used as a constant to initialize the size of the packet sent. This constant likely needs to be removed and the logic around it changed.

https://github.com/sparrc/go-ping/blob/ef3ab45e41b017889941ea5bb796dd502d2b5a1b/ping.go#L514

**Comment by SuperQ** [comment]
Yea, that bit didn't look right to me at all, but I didn't have time to poke around.

**Comment by CHTJonas** [comment]
Using the latest commit on `master` and with `sudo tcpdump icmp` running in another terminal tab:

- `pinger.Size = 256` logs an ICMP echo request packet with length 264.
- `pinger.Size = 321` logs an ICMP echo request packet with length 329.
- `pinger.Size = 322` logs an ICMP echo request packet with length 330.
- `pinger.Size = 1472` logs an ICMP echo request packet with length 1480.

ICMP packets have an 8-byte header so this all seams correct to me.

If you set a (IMHO silly) packet size `pinger.Size = 60000` (or indeed anything above 1472 in most instances) then the ICMP datagram gets fragmented across multiple IP packets at the network MTU. I don't really think we can expect things to behave reliably is such circumstances so if the user sets Size > MTU then they get to keep both pieces.
