### ISSUE TITLE
Option to disable timeout

### ISSUE THREAD

**Issue by SuperQ** [go-ping/ping#41]
I'm working on a [long-running ping prober](https://github.com/SuperQ/smokeping_prober) and would like an option to disable the timeout.

I'm currently playing around with a replacement "Forever" channel function.

```go
type Forever struct {
       C <-chan int
}

func forever() *Forever {
       C := make(chan int)
       return &Forever{C: C}
}
```

**Comment by CHTJonas** [comment]
Fixed by #120 😉
