### ISSUE TITLE
Add packet timeout callback

### ISSUE THREAD

**Issue by sajal** [go-ping/ping#50]
I would like to be notified when a ping fails in a specified timeout.

Example I have a long running pinger hitting `8.8.8.8`, whenever a probe does not get a response within 1 second, I would like a callback to fire informing me of the same, so my code can do something with that information.

It appears that the only way to do so currently is call `Statistics()` regularly and do some math to figure out if something lossy happened recently or not.

**Comment by sparrc** [comment]
@sajal This is a good idea, feel free to comment on #51 as you see fit.

**Comment by chrisFang5** [comment]
@sparrc Is anyone solving this problem?
