### ISSUE TITLE
Is there a way to make Run() execute faster?

### ISSUE THREAD

**Issue by jftuga** [go-ping/ping#52]
```
package main
import (
    "fmt"
    "time"
    "github.com/sparrc/go-ping"
)
func main() {
    host := "192.168.2.1"
    pinger, _ := ping.NewPinger( host )
    pinger.Count = 1
    start := time.Now()
    pinger.Run()
    end := time.Now()
    fmt.Println("elapsed:", end.Sub(start))
    fmt.Println(pinger.Statistics())
}
```

Output:

```
elapsed: 101.549586ms
&{1 1 0 192.168.2.1 192.168.2.1 [1.427179ms] 1.427179ms 1.427179ms 1.427179ms 0s}
```

I am wondering if there is a way to make the Run() function execute faster.  The actual ping itself only take 1.43 ms, but the entire function takes 101 ms.  This seems like a lot of overhead.  Also, the call to time.Now() only takes about 980ns. I get similar results across Windows, Linux and MacOS.

How can the be sped up?

**Comment by texh** [comment]
Absolute rookie here, but it looks like [this](https://github.com/sparrc/go-ping/blob/master/ping.go#L399) is most likely the reason.

**Comment by sparrc** [comment]
I agree this is not ideal. I'll gladly accept PRs to speed things up. Another avenue to look into might be the use of `defer`, which I know has significant overhead.

This being said, your method of benchmarking may not be 100% accurate, it would be good if you could get numbers using Go's built-in benchmarking tools (see https://dave.cheney.net/2013/06/30/how-to-write-benchmarks-in-go)

**Comment by sparrc** [comment]
also see #44
