### ISSUE TITLE
Latency added when pinging en parallel (goroutine)

### ISSUE THREAD

**Issue by vicentroca** [go-ping/ping#53]
I'm trying ping in parallel a hole C class (254 ip addresses) but I realize the I need to add a few delay between the creation of every goroutine or otherwise the latency of every ping increases.
¿any ideas what could this be?
Thank you

**Comment by sparrc** [comment]
Could be a lot of things, including cpu or network congestion, what sort of latency numbers are you seeing with a few pingers vs. 254? Could you provide examples and maybe some steps to reproduce?

**Comment by vicentroca** [comment]
sure.
I'm testing my  idea with this code: https://paste.ofcode.org/VxHsjg3r4BPwrYsAdvgxmA
My idea is to be able to ping accurately as many hosts as possible.
On line 22 I add the delay.
Pinging these IP's without the delay I get about 26 ms, and with the delay I get about 2-3 ms
Pinging using the standard ping command is about 2-3 ms (they are local address to me)

Thanks for help :)

**Comment by sparrc** [comment]
I would guess the latency could be coming from the go runtime when suddenly launching 254 goroutines at the same time. It could also be that you are flooding your network interfaces with either ICMP or UDP packets.

The delay you're seeing doesn't seem too unreasonable to me given the circumstances, and I'm skeptical that it has anything to do with this library itself.

Are you able to run 254 parallel pings from your machine using the `ping` command? Does the delay have to be 1000 microseconds? Have you tried doing a random sleep from 10-1000 or so microseconds?
