### ISSUE TITLE
Count specifies packets received, not packets sent

### ISSUE THREAD

**Issue by KilleR** [go-ping/ping#6]
Count on Unix ping specifies the number of packets to send, whereas in this library, it waits for Count received packets.

This means that you will see more than the desired number of packets sent if you get any packet loss, or your ping time is higher than your interval.

Replicable if you run with the arguments "-c 10 -i 1ms"; you will see more than 10 packets sent, 10 packets received.

**Comment by sparrc** [comment]
I can fix it oversending packets easily, I will have to think about having it count based on number sent to make sure there are no unintended consequences. Most likely it means there needs to be a per-packet timeout.
