### ISSUE TITLE
Allow selection of IP address family

### ISSUE THREAD

**Issue by SuperQ** [go-ping/ping#64]
Currently the `NewPinger()` defaults to automatic "ip" network selection. It would be useful to be explicit about selecting IPv4 vs IPv6, Then the ping cmd can allow for flags `-4` and `-6` to enforce which mode to use.

The simplest way would be to change it to something like:

```go
func NewPinger(n string, addr string) (*Pinger, error) {
  ipaddr, err := net.ResolveIPAddr(n, addr)
```

**Comment by sparrc** [comment]
that sounds good, we probably want to create a new builder function with an options struct so as not to break backwards compatability. ie 

```go
func NewPingerWithOpts(addr string, opts PingerOptions) (*Pinger, error) {
```

**Comment by SuperQ** [comment]
Yea, that sounds fine.
