### ISSUE TITLE
ping.Statistics is not thread-safe

### ISSUE THREAD

**Issue by Darigaaz** [go-ping/ping#74]
ping.Statistics docs says `This can be run while the pinger is running or after it is finished`
https://github.com/sparrc/go-ping/blob/4e5b6552494c8005c60de6c60b50ebaefc69e592/ping.go#L356-L359

But the only safe places to run ping.Statistics are in ping.OnRecv and ping.OnFinish.
There is no sync mechanics to protect fields like `PacketsRecv`, `PacketsSent`, `Rtts` while they are being updated in `processPacket`

Imagine your `pinger.Run` goroutine is rescheduled and put to sleep just before  https://github.com/sparrc/go-ping/blob/4e5b6552494c8005c60de6c60b50ebaefc69e592/ping.go#L499  PacketsRecv is updated, but `Rtts` is not. And your another goroutine calls `pinger.Statistics` on the same pinger  - it will get inconsistent data.

But there is more, as far as I know, gouroutines can be rescheduled in the middle of statement, like `p.PacketsSent++` or `append`. Then call to `Statistics` will read corrupted data.

Options:
1) Fix `Statistics` to be thread-safe
2) Fix godoc on `Statistics`

**Comment by sparrc** [comment]
wow that is an interesting avatar....but yes you are correct, this should be fixed probably with a semaphore

**Comment by SuperQ** [comment]
This should be fixed by https://github.com/go-ping/ping/pull/150 and https://github.com/go-ping/ping/pull/151.
