### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by perry-amsterdam** [go-ping/ping#88]
Hi i created the following go function.
When i do not use a timeout, it works. When i set a timeout it says one packet send 0 recieved.
Then it stops.
Perry

// Test internet connection by sending 3 pings to www.google.com.
func testInternet(hostname string) (ok bool) {

	pinger, err := ping.NewPinger(hostname)
	if err != nil {
		fmt.Printf("ERROR: %s\n", err.Error())
		return
	}

	pinger.OnRecv = func(pkt *ping.Packet) {
		fmt.Printf("%d bytes from %s: icmp_seq=%d time=%v\n", pkt.Nbytes, pkt.IPAddr, pkt.Seq, pkt.Rtt)
	}

	pinger.OnFinish = func(stats *ping.Statistics) {
		fmt.Printf("\n--- %s ping statistics ---\n", stats.Addr)
		fmt.Printf("%d packets transmitted, %d packets received, %v%% packet loss\n", stats.PacketsSent, stats.PacketsRecv, stats.PacketLoss)
		fmt.Printf("round-trip min/avg/max/stddev = %v/%v/%v/%v\n", stats.MinRtt, stats.AvgRtt, stats.MaxRtt, stats.StdDevRtt)
	}

	fmt.Printf("PING %s (%s):\n", pinger.Addr(), pinger.IPAddr())

	pinger.Count = 3
	pinger.Timeout =  5 * 100000
	pinger.SetPrivileged(true)
	pinger.Run()

	fmt.Printf("Package Send : %d, Package Recieved %d\n", pinger.PacketsSent, pinger.PacketsRecv)

	return (pinger.PacketsRecv > 0)
}

**Comment by tanghaifeng** [comment]
pinger.Timeout = time.Second

**Comment by tanghaifeng** [comment]
> Hi i created the following go function.
> When i do not use a timeout, it works. When i set a timeout it says one packet send 0 recieved.
> Then it stops.
> Perry
> 
> // Test internet connection by sending 3 pings to [www.google.com](http://www.google.com).
> func testInternet(hostname string) (ok bool) {
> 
> ```
> pinger, err := ping.NewPinger(hostname)
> if err != nil {
> 	fmt.Printf("ERROR: %s\n", err.Error())
> 	return
> }
> 
> pinger.OnRecv = func(pkt *ping.Packet) {
> 	fmt.Printf("%d bytes from %s: icmp_seq=%d time=%v\n", pkt.Nbytes, pkt.IPAddr, pkt.Seq, pkt.Rtt)
> }
> 
> pinger.OnFinish = func(stats *ping.Statistics) {
> 	fmt.Printf("\n--- %s ping statistics ---\n", stats.Addr)
> 	fmt.Printf("%d packets transmitted, %d packets received, %v%% packet loss\n", stats.PacketsSent, stats.PacketsRecv, stats.PacketLoss)
> 	fmt.Printf("round-trip min/avg/max/stddev = %v/%v/%v/%v\n", stats.MinRtt, stats.AvgRtt, stats.MaxRtt, stats.StdDevRtt)
> }
> 
> fmt.Printf("PING %s (%s):\n", pinger.Addr(), pinger.IPAddr())
> 
> pinger.Count = 3
> pinger.Timeout =  5 * 100000
> pinger.SetPrivileged(true)
> pinger.Run()
> 
> fmt.Printf("Package Send : %d, Package Recieved %d\n", pinger.PacketsSent, pinger.PacketsRecv)
> 
> return (pinger.PacketsRecv > 0)
> ```
> 
> }

pinger.Timeout = time.Second

**Comment by CHTJonas** [comment]
In Go, a timeout of `5 * 100000` is actually equal to `0.5 * time.Millisecond` which is likely far too short a time for packets to traverse the Internet. See https://golang.org/pkg/time/#pkg-constants for more details.
