### ISSUE TITLE
Call for volunteers: please comment if you are interested in helping maintain go-ping.

### ISSUE THREAD

**Issue by CHTJonas** [go-ping/ping#90]
There are a variety of open issues and pull requests, most dating back to early 2019 but some as far as 2017. Additionally there have been no commits in over a year.

Are you still interested in maintaining this, @sparrc? If not, would you be amenable to giving commit rights to others?

What is the plan for `go-ping`?

**Comment by SuperQ** [comment]
I also have the same question. I've been thinking about making a permanent fork, as I use this for one of my projects.

**Comment by sparrc** [comment]
Apologies, I have been considering soliciting for help in maintaining this project. My first child was born in early-2019 and I no longer have enough free time outside of work to maintain this myself, as has clearly been noticed.

I will change the title of this issue as a call for volunteers to help in maintaining this project, as I'd rather not see it abandoned.

@SuperQ I'm assuming you are interested?

**Comment by SuperQ** [comment]
Yes, I'm interested.

**Comment by SuperQ** [comment]
Ping @sparrc :smile:

**Comment by CHTJonas** [comment]
I'd also potentially be interested in helping out if you feel more hands are needed 👍

**Comment by sparrc** [comment]
I think it'd be easier to coordinate this if we were able to chat in real-time. Are you both able to join the gophers slack workspace? We can chat there in channel #go-ping, and we can also use that as a place for people to go for support and questions.

Not sure if there's a better workspace than gophers.slack.com, but it still seems fairly active, you can join by going here: https://gophers.slack.com/join/shared_invite/zt-fajz7jh3-2cpkmFU~hQb8d5LmOCnhfQ#/

**Comment by SuperQ** [comment]
Ugh, more slacks to sign up for. I'm happy to setup a Zoom/Meet/Jitsi call some time. I'm on EU central time.

**Comment by sparrc** [comment]
I would prefer to have a method of continuous chat communication for now. Gophers slack seems to me to be the most logical place but I'm open to other venues too.

**Comment by pgollangi** [comment]
gophers link seems to be no longer active

**Comment by sparrc** [comment]
@pgollangi try this: https://invite.slack.golangbridge.org/

**Comment by sparrc** [comment]
This repo has now been transferred to the go-ping organization
