### ISSUE TITLE
Run should return an error when setup fails

### ISSUE THREAD

**Issue by ks07** [go-ping/ping#92]
The [issues with raw socket support](https://github.com/sparrc/go-ping#note-on-linux-support) means that if the caller does not set privileged mode correctly, or if the user runs the executable without the required capab, the `Pinger.Run()` method can return immediately without sending any ping packets.

There is currently no direct way of differentiating between these problems caused by an invalid environment versus a successful run, as there is no return value from `Run`. The code simply logs the error to stdout, which isn't very helpful.

As a workaround, you can either check that `Statistics.PacketsSent` is non-zero, or you can check for the invocation of the `OnFinish` handler, which won't get invoked if setting up the ICMP listener fails, although neither of these are ideal.

I think `Run` should return an error in these circumstances, although sadly this would break backwards compat on the interface.

**Comment by CHTJonas** [comment]
`pinger.Run()` now returns an error as of #81.
