### ISSUE TITLE
Pinger.Stop() is unsafe when used with a timeout or count

### ISSUE THREAD

**Issue by ks07** [go-ping/ping#94]
Calling the `Stop()` method on a pinger with a timeout or count configured can cause a panic, if the `Stop()` is called after the Pinger has exceeded either the timeout or ping count:

```
panic: close of closed channel

goroutine 10 [running]:
github.com/sparrc/go-ping.(*Pinger).Stop(...)
	/go/pkg/mod/github.com/sparrc/go-ping@v0.0.0-20190613174326-4e5b6552494c/ping.go:345
```

There's no way to safely prevent this panic externally without some kind of race condition.

**Comment by ks07** [comment]
It looks like #83 by @voidint already fixes this issue with a `sync.Once`

**Comment by CHTJonas** [comment]
Unable to reproduce, I'm afraid. If you can provide a concrete example that fails when using the latest commit on `master` then we can reopen.

**Comment by ks07** [comment]
The issue is that the internal timeout and packet counting mechanisms close the `p.done` channel, which `Stop()` also closes. You can reproduce with a contrived example like:

https://gist.github.com/ks07/4f9a57af233027b194801323017b0141

```
2020/10/17 17:33:45 24 bytes from 8.8.8.8: icmp_seq=0 time=31.0067ms
panic: close of closed channel

goroutine 9 [running]:
github.com/go-ping/ping.(*Pinger).Stop(...)
	C:/Users/George/go/pkg/mod/github.com/go-ping/ping@v0.0.0-20201008161548-5f9dc3248bce/ping.go:381
main.main.func2()
	C:/Users/George/go/src/pingerExample/main.go:30 +0x5d
created by time.goFunc
	C:/Programs/Go/src/time/sleep.go:167 +0x4b

Process finished with exit code 2
```

In a real world use case the `time.AfterFunc()` call would be some other cancellation method handled in a separate goroutine.

**Comment by CHTJonas** [comment]
I see what's going on there. The `time.AfterFunc()` could be an interrupt handler, for example, which might race if the user hits Ctrl+C at or near the configured `pinger.Timeout`.

I wonder whether `pinger.Stop()` could be made to return an error in cases when it is called more than once and/or whether this is actually useful to anyone?
